# Generated by Django 4.0.4 on 2022-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Anime', 'Anime'), ('Romantic', 'Romantic'), ('Action', 'Action')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('age_control', models.PositiveIntegerField()),
            ],
        ),
    ]
