# Generated by Django 4.0.4 on 2022-06-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0002_dorama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dorama',
            options={'verbose_name': 'Дорама', 'verbose_name_plural': 'Дорамалар'},
        ),
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name': 'Искусственное растение', 'verbose_name_plural': 'Искусственные Растения'},
        ),
    ]
